version: '3.8'

services:
  simulator:
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    networks:
      - iot-network
    restart: always

  broker:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "61616:61616" # Porta per il protocollo CORE/OpenWire
      - "1883:1883"   # Porta per il protocollo MQTT (fondamentale per i sensori)
      - "61613:61613"
      - "8161:8161"   # Console Web (Dashboard di controllo)
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin_password
      - ANONYMOUS_LOGIN=true
    networks:
      - iot-network

  ingestion-service:
    build: ./ingestion
    networks:
      - iot-network 
    depends_on:
      - simulator
      - broker
    environment:
      - PYTHONUNBUFFERED=1 

  processing:
    build: ./processing
    container_name: processing_service
    depends_on:
      - broker
      - db
    networks:
      - iot-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mars_iot
      MYSQL_USER: user_mars
      MYSQL_PASSWORD: password_mars
    volumes:
      # Script di inizializzazione
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # Cartella fisica per i dati 
      - ./db/data:/var/lib/mysql
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge